candidates = 2
voters = 3001 # prime

[[considerations]]
[[considerations.Issues]]
halfcsep = 0.0
halfvsep = 0.0
sigma = 0.5773502691896258
uniform = true

[[methods]]
[methods.Plurality]
strat = "Honest"

[[methods]]
[methods.Plurality]
strat = "Strategic"

[[methods]]
[methods.InstantRunoff]

[[methods]]
[methods.Range]
nranks = 2
strat = "Honest"

[[methods]]
[methods.Range]
nranks = 2
strat = "Strategic"

[[methods]]
[methods.STAR]
strat = "Honest"

[[methods]]
[methods.STAR]
strat = "Strategic"
strategic_stretch_factor = 2.0

[[methods]]
[methods.BtrIrv]
strat = "Honest"

[[methods]]
[methods.RP]
strat = "Honest"
